#!/bin/bash

if [[ `git symbolic-ref HEAD` == "refs/heads/releases" ]]
then
    echo "You cannot commit to releases!"
    echo "Stash your changes and apply them to another branch"
    echo "git stash"
    echo "git checkout <branch>"
    echo "git stash pop"
    exit 1
fi

